// ── Quote of the day ─────────────────────────────────────────────
// A local, static list — no network call, no API key. The quote shown is a
// pure function of the calendar day, so every device lands on the same one
// without any syncing: pick a day-count, index into the list, done.
//
// QUOTES.length is deliberately not a round number like 365: if it divided
// evenly into a year, the exact same quote would land on the exact same
// calendar date every year, forever. An irregular length drifts the mapping
// year over year instead.
const QUOTES = [
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { q: "It always seems impossible until it's done.", a: "Nelson Mandela" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
  { q: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill" },
  { q: "In the middle of difficulty lies opportunity.", a: "Albert Einstein" },
  { q: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius" },
  { q: "Whether you think you can, or you think you can't, you're right.", a: "Henry Ford" },
  { q: "The only limit to our realization of tomorrow will be our doubts of today.", a: "Franklin D. Roosevelt" },
  { q: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson" },
  { q: "The best way to predict the future is to create it.", a: "Abraham Lincoln" },
  { q: "Do not go where the path may lead, go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson" },
  { q: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", a: "Mark Twain" },
  { q: "The secret of getting ahead is getting started.", a: "Mark Twain" },
  { q: "Continuous effort, not strength or intelligence, is the key to unlocking our potential.", a: "Winston Churchill" },
  { q: "Believe you can and you're halfway there.", a: "Theodore Roosevelt" },
  { q: "Nothing in the world can take the place of persistence.", a: "Calvin Coolidge" },
  { q: "The man who moves a mountain begins by carrying away small stones.", a: "Confucius" },
  { q: "A journey of a thousand miles begins with a single step.", a: "Lao Tzu" },
  { q: "Knowing yourself is the beginning of all wisdom.", a: "Aristotle" },
  { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Aristotle" },
  { q: "The unexamined life is not worth living.", a: "Socrates" },
  { q: "Wonder is the beginning of wisdom.", a: "Socrates" },
  { q: "He who has a why to live can bear almost any how.", a: "Friedrich Nietzsche" },
  { q: "That which does not kill us makes us stronger.", a: "Friedrich Nietzsche" },
  { q: "You have power over your mind, not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius" },
  { q: "Waste no more time arguing about what a good man should be. Be one.", a: "Marcus Aurelius" },
  { q: "It is not that we have a short time to live, but that we waste a lot of it.", a: "Seneca" },
  { q: "Luck is what happens when preparation meets opportunity.", a: "Seneca" },
  { q: "No man is free who is not master of himself.", a: "Epictetus" },
  { q: "First say to yourself what you would be, and then do what you have to do.", a: "Epictetus" },
  { q: "The mind is everything. What you think you become.", a: "Buddha" },
  { q: "Three things cannot be long hidden: the sun, the moon, and the truth.", a: "Buddha" },
  { q: "Peace comes from within. Do not seek it without.", a: "Buddha" },
  { q: "A journey of a thousand miles must begin with a single step.", a: "Lao Tzu" },
  { q: "When I let go of what I am, I become what I might be.", a: "Lao Tzu" },
  { q: "Know yourself and you will win all battles.", a: "Sun Tzu" },
  { q: "Opportunities multiply as they are seized.", a: "Sun Tzu" },
  { q: "Learning without thought is labor lost; thought without learning is perilous.", a: "Confucius" },
  { q: "Our greatest glory is not in never falling, but in rising every time we fall.", a: "Confucius" },
  { q: "Life is 10% what happens to us and 90% how we react to it.", a: "Charles Swindoll" },
  { q: "Imagination is more important than knowledge.", a: "Albert Einstein" },
  { q: "Try not to become a person of success, but rather try to become a person of value.", a: "Albert Einstein" },
  { q: "Life is like riding a bicycle. To keep your balance you must keep moving.", a: "Albert Einstein" },
  { q: "A person who never made a mistake never tried anything new.", a: "Albert Einstein" },
  { q: "Once you replace negative thoughts with positive ones, you'll start having positive results.", a: "Willie Nelson" },
  { q: "Optimism is the faith that leads to achievement. Nothing can be done without hope.", a: "Helen Keller" },
  { q: "Although the world is full of suffering, it is also full of the overcoming of it.", a: "Helen Keller" },
  { q: "Alone we can do so little; together we can do so much.", a: "Helen Keller" },
  { q: "Character cannot be developed in ease and quiet.", a: "Helen Keller" },
  { q: "The only thing worse than being blind is having sight but no vision.", a: "Helen Keller" },
  { q: "You must do the thing you think you cannot do.", a: "Eleanor Roosevelt" },
  { q: "No one can make you feel inferior without your consent.", a: "Eleanor Roosevelt" },
  { q: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", a: "Eleanor Roosevelt" },
  { q: "It is during our darkest moments that we must focus to see the light.", a: "Aristotle" },
  { q: "Do the best you can until you know better. Then when you know better, do better.", a: "Maya Angelou" },
  { q: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", a: "Maya Angelou" },
  { q: "Try to be a rainbow in someone's cloud.", a: "Maya Angelou" },
  { q: "Nothing will work unless you do.", a: "Maya Angelou" },
  { q: "There is no greater agony than bearing an untold story inside you.", a: "Maya Angelou" },
  { q: "Education is the most powerful weapon which you can use to change the world.", a: "Nelson Mandela" },
  { q: "I never lose. I either win or learn.", a: "Nelson Mandela" },
  { q: "The greatest glory in living lies not in never falling, but in rising every time we fall.", a: "Nelson Mandela" },
  { q: "May you live every day of your life.", a: "Jonathan Swift" },
  { q: "Be the change that you wish to see in the world.", a: "Mahatma Gandhi" },
  { q: "The weak can never forgive. Forgiveness is the attribute of the strong.", a: "Mahatma Gandhi" },
  { q: "Live as if you were to die tomorrow. Learn as if you were to live forever.", a: "Mahatma Gandhi" },
  { q: "Strength does not come from physical capacity. It comes from an indomitable will.", a: "Mahatma Gandhi" },
  { q: "Your beliefs become your thoughts. Your thoughts become your words. Your words become your actions.", a: "Mahatma Gandhi" },
  { q: "Darkness cannot drive out darkness; only light can do that.", a: "Martin Luther King Jr." },
  { q: "Faith is taking the first step even when you don't see the whole staircase.", a: "Martin Luther King Jr." },
  { q: "The time is always right to do what is right.", a: "Martin Luther King Jr." },
  { q: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but keep moving.", a: "Martin Luther King Jr." },
  { q: "Our lives begin to end the day we become silent about things that matter.", a: "Martin Luther King Jr." },
  { q: "I have a dream that one day this nation will rise up and live out the true meaning of its creed.", a: "Martin Luther King Jr." },
  { q: "One person can make a difference, and everyone should try.", a: "John F. Kennedy" },
  { q: "Ask not what your country can do for you; ask what you can do for your country.", a: "John F. Kennedy" },
  { q: "Efforts and courage are not enough without purpose and direction.", a: "John F. Kennedy" },
  { q: "Things do not happen. Things are made to happen.", a: "John F. Kennedy" },
  { q: "There is nothing wrong with change, if it is in the right direction.", a: "Winston Churchill" },
  { q: "Success is walking from failure to failure with no loss of enthusiasm.", a: "Winston Churchill" },
  { q: "Never, never, never give up.", a: "Winston Churchill" },
  { q: "Attitude is a little thing that makes a big difference.", a: "Winston Churchill" },
  { q: "To improve is to change; to be perfect is to change often.", a: "Winston Churchill" },
  { q: "History will be kind to me for I intend to write it.", a: "Winston Churchill" },
  { q: "Genius is one percent inspiration and ninety-nine percent perspiration.", a: "Thomas Edison" },
  { q: "Many of life's failures are people who did not realize how close they were to success when they gave up.", a: "Thomas Edison" },
  { q: "I have not failed. I've just found 10,000 ways that won't work.", a: "Thomas Edison" },
  { q: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", a: "Thomas Edison" },
  { q: "If we did all the things we are capable of, we would literally astound ourselves.", a: "Thomas Edison" },
  { q: "Coming together is a beginning; keeping together is progress; working together is success.", a: "Henry Ford" },
  { q: "Failure is simply the opportunity to begin again, this time more intelligently.", a: "Henry Ford" },
  { q: "Obstacles are those frightful things you see when you take your eyes off your goal.", a: "Henry Ford" },
  { q: "Quality means doing it right when no one is looking.", a: "Henry Ford" },
  { q: "The way to get started is to quit talking and begin doing.", a: "Walt Disney" },
  { q: "All our dreams can come true, if we have the courage to pursue them.", a: "Walt Disney" },
  { q: "If you can dream it, you can do it.", a: "Walt Disney" },
  { q: "It's kind of fun to do the impossible.", a: "Walt Disney" },
  { q: "The more you like yourself, the less you are like anyone else, which makes you unique.", a: "Walt Disney" },
  { q: "Stay hungry, stay foolish.", a: "Steve Jobs" },
  { q: "Your work is going to fill a large part of your life, so do work you believe is great.", a: "Steve Jobs" },
  { q: "Innovation distinguishes between a leader and a follower.", a: "Steve Jobs" },
  { q: "Sometimes life hits you in the head with a brick. Don't lose faith.", a: "Steve Jobs" },
  { q: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { q: "Your most unhappy customers are your greatest source of learning.", a: "Bill Gates" },
  { q: "It's fine to celebrate success but it is more important to heed the lessons of failure.", a: "Bill Gates" },
  { q: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", a: "Bill Gates" },
  { q: "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself.", a: "Bill Gates" },
  { q: "Risk comes from not knowing what you're doing.", a: "Warren Buffett" },
  { q: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", a: "Warren Buffett" },
  { q: "Someone is sitting in the shade today because someone planted a tree a long time ago.", a: "Warren Buffett" },
  { q: "The most important investment you can make is in yourself.", a: "Warren Buffett" },
  { q: "Chains of habit are too light to be felt until they are too heavy to be broken.", a: "Warren Buffett" },
  { q: "If you're not embarrassed by the first version of your product, you've launched too late.", a: "Reid Hoffman" },
  { q: "Fail fast, fail often, and fail forward.", a: "John C. Maxwell" },
  { q: "Life shrinks or expands in proportion to one's courage.", a: "Anaïs Nin" },
  { q: "You must be the change you wish to see in the world.", a: "Mahatma Gandhi" },
  { q: "It is our choices that show what we truly are, far more than our abilities.", a: "J.K. Rowling" },
  { q: "We do not need magic to change the world; we carry all the power we need inside ourselves already.", a: "J.K. Rowling" },
  { q: "Rock bottom became the solid foundation on which I rebuilt my life.", a: "J.K. Rowling" },
  { q: "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all.", a: "J.K. Rowling" },
  { q: "Fairy tales are more than true: not because they tell us dragons exist, but because they tell us dragons can be beaten.", a: "G.K. Chesterton" },
  { q: "Not all those who wander are lost.", a: "J.R.R. Tolkien" },
  { q: "All we have to decide is what to do with the time that is given us.", a: "J.R.R. Tolkien" },
  { q: "Even the smallest person can change the course of the future.", a: "J.R.R. Tolkien" },
  { q: "There is some good in this world, and it's worth fighting for.", a: "J.R.R. Tolkien" },
  { q: "Even the darkest night will end and the sun will rise.", a: "Victor Hugo" },
  { q: "Nothing is more powerful than an idea whose time has come.", a: "Victor Hugo" },
  { q: "Great deeds are usually wrought at great risks.", a: "Herodotus" },
  { q: "Courage is the first of human qualities because it is the quality which guarantees all others.", a: "Winston Churchill" },
  { q: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt" },
  { q: "It is hard to fail, but it is worse never to have tried to succeed.", a: "Theodore Roosevelt" },
  { q: "Nothing worth having comes easy.", a: "Theodore Roosevelt" },
  { q: "Keep your eyes on the stars, and your feet on the ground.", a: "Theodore Roosevelt" },
  { q: "Comparison is the thief of joy.", a: "Theodore Roosevelt" },
  { q: "Far and away the best prize that life offers is the chance to work hard at work worth doing.", a: "Theodore Roosevelt" },
  { q: "The only thing we have to fear is fear itself.", a: "Franklin D. Roosevelt" },
  { q: "When you reach the end of your rope, tie a knot in it and hang on.", a: "Franklin D. Roosevelt" },
  { q: "Happiness lies in the joy of achievement and the thrill of creative effort.", a: "Franklin D. Roosevelt" },
  { q: "A smooth sea never made a skilled sailor.", a: "Franklin D. Roosevelt" },
  { q: "Courage is not the absence of fear, but the triumph over it.", a: "Nelson Mandela" },
  { q: "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.", a: "William James" },
  { q: "Act as if what you do makes a difference. It does.", a: "William James" },
  { q: "The greatest weapon against stress is our ability to choose one thought over another.", a: "William James" },
  { q: "Act the way you'd like to be and soon you'll be the way you act.", a: "William James" },
  { q: "The only way out is through.", a: "Robert Frost" },
  { q: "Two roads diverged in a wood, and I took the one less traveled by.", a: "Robert Frost" },
  { q: "In three words I can sum up everything I've learned about life: it goes on.", a: "Robert Frost" },
  { q: "I took the road less traveled by, and that has made all the difference.", a: "Robert Frost" },
  { q: "Hope is the thing with feathers that perches in the soul.", a: "Emily Dickinson" },
  { q: "Forever is composed of nows.", a: "Emily Dickinson" },
  { q: "Not knowing when the dawn will come, I open every door.", a: "Emily Dickinson" },
  { q: "Dwell in possibility.", a: "Emily Dickinson" },
  { q: "You can't wait for inspiration. You have to go after it with a club.", a: "Jack London" },
  { q: "The function of muscle is to pull and not to push, except in the case of the genitals and the tongue.", a: "Leonardo da Vinci" },
  { q: "Simplicity is the ultimate sophistication.", a: "Leonardo da Vinci" },
  { q: "Learning never exhausts the mind.", a: "Leonardo da Vinci" },
  { q: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them.", a: "Leonardo da Vinci" },
  { q: "I love those who yearn for the impossible.", a: "Johann Wolfgang von Goethe" },
  { q: "Whatever you can do, or dream you can, begin it. Boldness has genius, power, and magic in it.", a: "Johann Wolfgang von Goethe" },
  { q: "Knowing is not enough; we must apply. Willing is not enough; we must do.", a: "Johann Wolfgang von Goethe" },
  { q: "Genius is nothing but a great aptitude for patience.", a: "Georges-Louis Leclerc de Buffon" },
  { q: "Patience is bitter, but its fruit is sweet.", a: "Aristotle" },
  { q: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", a: "Aristotle" },
  { q: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", a: "Aristotle" },
  { q: "Pleasure in the job puts perfection in the work.", a: "Aristotle" },
  { q: "The energy of the mind is the essence of life.", a: "Aristotle" },
  { q: "For the things we have to learn before we can do them, we learn by doing them.", a: "Aristotle" },
  { q: "Educating the mind without educating the heart is no education at all.", a: "Aristotle" },
  { q: "True knowledge exists in knowing that you know nothing.", a: "Socrates" },
  { q: "The only true wisdom is in knowing you know nothing.", a: "Socrates" },
  { q: "An unexamined life is not worth living.", a: "Socrates" },
  { q: "Be kind, for everyone you meet is fighting a hard battle.", a: "Plato" },
  { q: "The beginning is the most important part of the work.", a: "Plato" },
  { q: "Courage is knowing what not to fear.", a: "Plato" },
  { q: "Human behavior flows from three main sources: desire, emotion, and knowledge.", a: "Plato" },
  { q: "Wise men speak because they have something to say; fools because they have to say something.", a: "Plato" },
  { q: "At the touch of love, everyone becomes a poet.", a: "Plato" },
  { q: "Well begun is half done.", a: "Aristotle" },
  { q: "It is the little things that matter most.", a: "Arthur Conan Doyle" },
  { q: "Mediocrity knows nothing higher than itself, but talent instantly recognizes genius.", a: "Arthur Conan Doyle" },
  { q: "Never trust to general impressions, my boy, but concentrate yourself upon details.", a: "Arthur Conan Doyle" },
  { q: "It is a capital mistake to theorize before one has data.", a: "Arthur Conan Doyle" },
  { q: "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.", a: "Arthur Conan Doyle" },
  { q: "Everything you've ever wanted is on the other side of fear.", a: "George Addair" },
  { q: "Doubt kills more dreams than failure ever will.", a: "Suzy Kassem" },
  { q: "Failure is the condiment that gives success its flavor.", a: "Truman Capote" },
  { q: "Success is not the key to happiness. Happiness is the key to success.", a: "Albert Schweitzer" },
  { q: "None of us knows what might happen even the next minute, yet still we go forward.", a: "Paulo Coelho" },
  { q: "When you want something, all the universe conspires in helping you to achieve it.", a: "Paulo Coelho" },
  { q: "It's the possibility of having a dream come true that makes life interesting.", a: "Paulo Coelho" },
  { q: "There is only one thing that makes a dream impossible to achieve: the fear of failure.", a: "Paulo Coelho" },
  { q: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", a: "Socrates" },
  { q: "Be yourself; everyone else is already taken.", a: "Oscar Wilde" },
  { q: "To live is the rarest thing in the world. Most people exist, that is all.", a: "Oscar Wilde" },
  { q: "We are all in the gutter, but some of us are looking at the stars.", a: "Oscar Wilde" },
  { q: "Yet each man kills the thing he loves.", a: "Oscar Wilde" },
  { q: "The truth is rarely pure and never simple.", a: "Oscar Wilde" },
  { q: "Experience is simply the name we give our mistakes.", a: "Oscar Wilde" },
  { q: "Life is never fair, and perhaps it is a good thing for most of us that it is not.", a: "Oscar Wilde" },
  { q: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", a: "George Bernard Shaw" },
  { q: "Life isn't about finding yourself. Life is about creating yourself.", a: "George Bernard Shaw" },
  { q: "The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself.", a: "George Bernard Shaw" },
  { q: "Success does not consist in never making mistakes but in never making the same one a second time.", a: "George Bernard Shaw" },
  { q: "Imagination is the beginning of creation.", a: "George Bernard Shaw" },
  { q: "Nothing can be more absurd than to believe that all these effects could be produced by chance.", a: "Isaac Newton" },
  { q: "If I have seen further it is by standing on the shoulders of giants.", a: "Isaac Newton" },
  { q: "Tact is the art of making a point without making an enemy.", a: "Isaac Newton" },
  { q: "We build too many walls and not enough bridges.", a: "Isaac Newton" },
  { q: "Look deep into nature, and then you will understand everything better.", a: "Albert Einstein" },
  { q: "Somewhere, something incredible is waiting to be known.", a: "Carl Sagan" },
  { q: "The nitrogen in our DNA, the calcium in our teeth, the iron in our blood were made in the interiors of collapsing stars.", a: "Carl Sagan" },
  { q: "For small creatures such as we, the vastness is bearable only through love.", a: "Carl Sagan" },
  { q: "Extraordinary claims require extraordinary evidence.", a: "Carl Sagan" },
  { q: "We are a way for the cosmos to know itself.", a: "Carl Sagan" },
  { q: "However difficult life may seem, there is always something you can do and succeed at.", a: "Stephen Hawking" },
  { q: "Look up at the stars and not down at your feet.", a: "Stephen Hawking" },
  { q: "Intelligence is the ability to adapt to change.", a: "Stephen Hawking" },
  { q: "Remember to look up at the stars and not down at your feet.", a: "Stephen Hawking" },
  { q: "My philosophy is: it can be done.", a: "Nikola Tesla" },
  { q: "The present is theirs; the future, for which I really worked, is mine.", a: "Nikola Tesla" },
  { q: "The scientists of today think deeply instead of clearly.", a: "Nikola Tesla" },
  { q: "Our virtues and our failings are inseparable, like force and matter.", a: "Nikola Tesla" },
  { q: "A ship in harbor is safe, but that is not what ships are built for.", a: "John A. Shedd" },
  { q: "Discipline is choosing between what you want now and what you want most.", a: "Abraham Lincoln" },
  { q: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", a: "Abraham Lincoln" },
  { q: "Whatever you are, be a good one.", a: "Abraham Lincoln" },
  { q: "Always bear in mind that your own resolution to succeed is more important than any other one thing.", a: "Abraham Lincoln" },
  { q: "I am a slow walker, but I never walk back.", a: "Abraham Lincoln" },
  { q: "Things may come to those who wait, but only the things left by those who hustle.", a: "Abraham Lincoln" },
  { q: "You cannot escape the responsibility of tomorrow by evading it today.", a: "Abraham Lincoln" },
  { q: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", a: "Abraham Lincoln" },
  { q: "That some achieve great success, is proof to all that others can achieve it as well.", a: "Abraham Lincoln" },
  { q: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", a: "Benjamin Franklin" },
  { q: "An investment in knowledge pays the best interest.", a: "Benjamin Franklin" },
  { q: "By failing to prepare, you are preparing to fail.", a: "Benjamin Franklin" },
  { q: "Well done is better than well said.", a: "Benjamin Franklin" },
  { q: "Energy and persistence conquer all things.", a: "Benjamin Franklin" },
  { q: "Diligence is the mother of good luck.", a: "Benjamin Franklin" },
  { q: "Either write something worth reading or do something worth writing.", a: "Benjamin Franklin" },
  { q: "Never leave that till tomorrow which you can do today.", a: "Benjamin Franklin" },
  { q: "Life's tragedy is that we get old too soon and wise too late.", a: "Benjamin Franklin" },
  { q: "The definition of insanity is doing the same thing over and over and expecting different results.", a: "Rita Mae Brown" },
  { q: "Life is what happens when you're busy making other plans.", a: "John Lennon" },
  { q: "Every strike brings me closer to the next home run.", a: "Babe Ruth" },
  { q: "Never let the fear of striking out keep you from playing the game.", a: "Babe Ruth" },
  { q: "It's hard to beat a person who never gives up.", a: "Babe Ruth" },
  { q: "Yesterday's home runs don't win today's games.", a: "Babe Ruth" },
  { q: "The way a team plays as a whole determines its success.", a: "Babe Ruth" },
  { q: "Champions keep playing until they get it right.", a: "Billie Jean King" },
  { q: "Pressure is a privilege.", a: "Billie Jean King" },
  { q: "Winners never quit and quitters never win.", a: "Vince Lombardi" },
  { q: "It's not whether you get knocked down; it's whether you get up.", a: "Vince Lombardi" },
  { q: "Perfection is not attainable, but if we chase perfection we can catch excellence.", a: "Vince Lombardi" },
  { q: "The price of success is hard work, dedication, and an unremitting devotion to the things you want.", a: "Vince Lombardi" },
  { q: "Confidence is contagious. So is lack of confidence.", a: "Vince Lombardi" },
  { q: "Float like a butterfly, sting like a bee.", a: "Muhammad Ali" },
  { q: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", a: "Muhammad Ali" },
  { q: "It's the repetition of affirmations that leads to belief. Once that belief becomes a deep conviction, things begin to happen.", a: "Muhammad Ali" },
  { q: "He who is not courageous enough to take risks will accomplish nothing in life.", a: "Muhammad Ali" },
  { q: "A man who views the world the same at fifty as he did at twenty has wasted thirty years of his life.", a: "Muhammad Ali" },
  { q: "Impossible is just a word thrown around by small men.", a: "Muhammad Ali" },
  { q: "Champions aren't made in gyms. Champions are made from something they have deep inside them: a desire, a dream, a vision.", a: "Muhammad Ali" },
  { q: "I've missed more than 9,000 shots in my career. That is why I succeed.", a: "Michael Jordan" },
  { q: "Some people want it to happen, some wish it would happen, others make it happen.", a: "Michael Jordan" },
  { q: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up.", a: "Michael Jordan" },
  { q: "I can accept failure, everyone fails at something. But I can't accept not trying.", a: "Michael Jordan" },
  { q: "Talent wins games, but teamwork and intelligence win championships.", a: "Michael Jordan" },
  { q: "Be water, my friend.", a: "Bruce Lee" },
  { q: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", a: "Bruce Lee" },
  { q: "A goal is not always meant to be reached; it often serves simply as something to aim at.", a: "Bruce Lee" },
  { q: "Do not pray for an easy life; pray for the strength to endure a difficult one.", a: "Bruce Lee" },
  { q: "Notice that the stiffest tree is most easily cracked, while the bamboo survives by bending with the wind.", a: "Bruce Lee" },
  { q: "The successful warrior is the average man, with laser-like focus.", a: "Bruce Lee" },
  { q: "You miss 100% of the shots you don't take.", a: "Wayne Gretzky" },
  { q: "I skate to where the puck is going to be, not where it has been.", a: "Wayne Gretzky" },
  { q: "It's not about how good your best days are, it's how good your worst days are.", a: "Wayne Gretzky" },
  { q: "The highest reward for a person's toil is not what they get for it, but what they become by it.", a: "John Ruskin" },
  { q: "Quality is not an act, it is a habit.", a: "Aristotle" },
  { q: "The best preparation for tomorrow is doing your best today.", a: "H. Jackson Brown Jr." },
  { q: "Don't be afraid to give up the good to go for the great.", a: "John D. Rockefeller" },
  { q: "The road to success and the road to failure are almost exactly the same.", a: "Colin R. Davis" },
  { q: "Setting goals is the first step in turning the invisible into the visible.", a: "Tony Robbins" },
  { q: "The only impossible journey is the one you never begin.", a: "Tony Robbins" },
  { q: "It is in your moments of decision that your destiny is shaped.", a: "Tony Robbins" },
  { q: "Where focus goes, energy flows.", a: "Tony Robbins" },
  { q: "Success is doing ordinary things extraordinarily well.", a: "Jim Rohn" },
  { q: "Either you run the day, or the day runs you.", a: "Jim Rohn" },
  { q: "Motivation is what gets you started. Habit is what keeps you going.", a: "Jim Rohn" },
  { q: "You cannot change your destination overnight, but you can change your direction overnight.", a: "Jim Rohn" },
  { q: "Discipline is the bridge between goals and accomplishment.", a: "Jim Rohn" },
  { q: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", a: "Jim Rohn" },
  { q: "Formal education will make you a living; self-education will make you a fortune.", a: "Jim Rohn" },
  { q: "You are the average of the five people you spend the most time with.", a: "Jim Rohn" },
  { q: "Anything worth doing is worth doing badly at first.", a: "G.K. Chesterton" },
  { q: "There is no failure except in no longer trying.", a: "Elbert Hubbard" },
  { q: "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.", a: "Elbert Hubbard" },
  { q: "I always tried to turn every disaster into an opportunity.", a: "John D. Rockefeller" },
  { q: "Good management consists in showing average people how to do the work of superior people.", a: "John D. Rockefeller" },
  { q: "The way to develop self-confidence is to do the thing you fear and get a record of successful experiences behind you.", a: "William Jennings Bryan" },
  { q: "Fortune favors the bold.", a: "Virgil" },
  { q: "He conquers who endures.", a: "Persius" },
  { q: "The greatest wealth is to live content with little.", a: "Plato" },
  { q: "There is nothing permanent except change.", a: "Heraclitus" },
  { q: "No man ever steps in the same river twice.", a: "Heraclitus" },
  { q: "Big things have small beginnings.", a: "T.E. Lawrence" },
  { q: "Freedom is nothing but a chance to be better.", a: "Albert Camus" },
  { q: "In the depth of winter, I finally learned that within me there lay an invincible summer.", a: "Albert Camus" },
  { q: "You will never be happy if you continue to search for what happiness consists of.", a: "Albert Camus" },
  { q: "Life is the sum of all your choices.", a: "Albert Camus" },
  { q: "Man is not made for defeat.", a: "Ernest Hemingway" },
  { q: "The world breaks everyone, and afterward, many are strong at the broken places.", a: "Ernest Hemingway" },
  { q: "There is nothing to writing. All you do is sit down at a typewriter and bleed.", a: "Ernest Hemingway" },
  { q: "Courage is grace under pressure.", a: "Ernest Hemingway" },
  { q: "Never mistake motion for action.", a: "Ernest Hemingway" },
  { q: "It is good to have an end to journey toward; but it is the journey that matters, in the end.", a: "Ursula K. Le Guin" },
  { q: "So we beat on, boats against the current, borne back ceaselessly into the past.", a: "F. Scott Fitzgerald" },
  { q: "It is the loose ends with which men hang themselves.", a: "F. Scott Fitzgerald" },
  { q: "The test of a first-rate intelligence is the ability to hold two opposed ideas in mind at the same time.", a: "F. Scott Fitzgerald" },
  { q: "There are no second acts in American lives.", a: "F. Scott Fitzgerald" },
  { q: "You don't write because you want to say something, you write because you have something to say.", a: "F. Scott Fitzgerald" },
  { q: "The world is a fine place and worth fighting for.", a: "Ernest Hemingway" },
  { q: "It's not the load that breaks you down, it's the way you carry it.", a: "Lou Holtz" },
  { q: "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.", a: "Zig Ziglar" },
  { q: "You don't have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
  { q: "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", a: "Zig Ziglar" },
  { q: "Your attitude, not your aptitude, will determine your altitude.", a: "Zig Ziglar" },
  { q: "The most important key to achieving great success is to decide upon your goal and launch.", a: "Ludwig Mies van der Rohe" },
  { q: "You can't build a reputation on what you are going to do.", a: "Henry Ford" },
  { q: "There is joy in work. There is no happiness except in the realization that we have accomplished something.", a: "Henry Ford" },
  { q: "One who fears failure limits his activities.", a: "Henry Ford" },
  { q: "Vision without execution is just hallucination.", a: "Thomas Edison" },
  { q: "Show me a thoroughly satisfied man and I will show you a failure.", a: "Thomas Edison" },
  { q: "Just because something doesn't do what you planned it to do doesn't mean it's useless.", a: "Thomas Edison" },
  { q: "Everything comes to him who hustles while he waits.", a: "Thomas Edison" },
  { q: "Restlessness and discontent are the first necessities of progress.", a: "Thomas Edison" },
  { q: "The value of an idea lies in the using of it.", a: "Thomas Edison" },
  { q: "There is no substitute for hard work.", a: "Thomas Edison" },
  { q: "Discontent is the first necessity of progress.", a: "Thomas Edison" },
  { q: "I never did anything worth doing by accident.", a: "Thomas Edison" },
  { q: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", a: "Kobe Bryant" },
  { q: "Great things come from hard work and perseverance. No excuses.", a: "Kobe Bryant" },
  { q: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", a: "Kobe Bryant" },
  { q: "I can't relate to lazy people. We don't speak the same language.", a: "Kobe Bryant" },
  { q: "If you're afraid to fail, then you're probably going to fail.", a: "Kobe Bryant" },
  { q: "Rest at the end, not in the middle.", a: "Kobe Bryant" },
  { q: "Everything you've ever wanted is sitting on the other side of fear.", a: "Jack Canfield" },
  { q: "The magic you are looking for is in the work you are avoiding.", a: "Dipset (attributed proverb)" },
  { q: "Push yourself, because no one else is going to do it for you.", a: "Anonymous" },
  { q: "Great things never come from comfort zones.", a: "Anonymous" },
  { q: "Dream it. Wish it. Do it.", a: "Anonymous" },
  { q: "Success doesn't just find you. You have to go out and get it.", a: "Anonymous" },
  { q: "The harder you work for something, the greater you'll feel when you achieve it.", a: "Anonymous" },
  { q: "Don't stop when you're tired. Stop when you're done.", a: "David Goggins" },
  { q: "We are our choices.", a: "Jean-Paul Sartre" },
  { q: "Freedom is what you do with what's been done to you.", a: "Jean-Paul Sartre" },
  { q: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.", a: "Jean-Paul Sartre" },
  { q: "Life has no meaning a priori... It is up to you to give it a meaning.", a: "Jean-Paul Sartre" },
  { q: "He who has a why to live for can bear with almost any how.", a: "Friedrich Nietzsche" },
  { q: "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.", a: "Friedrich Nietzsche" },
  { q: "One must still have chaos in oneself to be able to give birth to a dancing star.", a: "Friedrich Nietzsche" },
  { q: "There are no facts, only interpretations.", a: "Friedrich Nietzsche" },
  { q: "What does not destroy me, makes me stronger.", a: "Friedrich Nietzsche" },
  { q: "Man's main task in life is to give birth to himself.", a: "Erich Fromm" },
  { q: "The good life is a process, not a state of being.", a: "Carl Rogers" },
  { q: "The curious paradox is that when I accept myself just as I am, then I can change.", a: "Carl Rogers" },
  { q: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", a: "Carl Jung" },
  { q: "Who looks outside, dreams; who looks inside, awakes.", a: "Carl Jung" },
  { q: "I am not what happened to me, I am what I choose to become.", a: "Carl Jung" },
  { q: "Everything that irritates us about others can lead us to an understanding of ourselves.", a: "Carl Jung" },
  { q: "Your visions will become clear only when you can look into your own heart.", a: "Carl Jung" },
  { q: "The privilege of a lifetime is to become who you truly are.", a: "Carl Jung" },
  { q: "Between stimulus and response there is a space. In that space is our power to choose our response.", a: "Viktor Frankl" },
  { q: "When we are no longer able to change a situation, we are challenged to change ourselves.", a: "Viktor Frankl" },
  { q: "Those who have a 'why' to live, can bear with almost any 'how'.", a: "Viktor Frankl" },
  { q: "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's own way.", a: "Viktor Frankl" },
  { q: "What is to give light must endure burning.", a: "Viktor Frankl" },
  { q: "Live as if you were living already for the second time.", a: "Viktor Frankl" },
  { q: "In some ways suffering ceases to be suffering at the moment it finds a meaning.", a: "Viktor Frankl" },
  { q: "I have found that among its other benefits, giving liberates the soul of the giver.", a: "Maya Angelou" },
  { q: "If you don't like something, change it. If you can't change it, change your attitude.", a: "Maya Angelou" },
  { q: "Success is liking yourself, liking what you do, and liking how you do it.", a: "Maya Angelou" },
  { q: "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.", a: "Maya Angelou" },
  { q: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.", a: "Maya Angelou" },
  { q: "My mission in life is not merely to survive, but to thrive.", a: "Maya Angelou" },
  { q: "History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.", a: "Maya Angelou" },
  { q: "We may encounter many defeats but we must not be defeated.", a: "Maya Angelou" },
  { q: "You alone are enough. You have nothing to prove to anybody.", a: "Maya Angelou" },
  { q: "Just living is not enough. One must have sunshine, freedom, and a little flower.", a: "Hans Christian Andersen" },
  { q: "Where there is love there is life.", a: "Mahatma Gandhi" },
  { q: "A man is but the product of his thoughts. What he thinks, he becomes.", a: "Mahatma Gandhi" },
  { q: "Freedom is not worth having if it does not include the freedom to make mistakes.", a: "Mahatma Gandhi" },
  { q: "First they ignore you, then they laugh at you, then they fight you, then you win.", a: "Mahatma Gandhi" },
  { q: "Almost everything you do will seem insignificant, but it is important that you do it.", a: "Mahatma Gandhi" },
  { q: "Action expresses priorities.", a: "Mahatma Gandhi" },
  { q: "You must not lose faith in humanity. Humanity is an ocean; if a few drops are dirty, the ocean does not become dirty.", a: "Mahatma Gandhi" },
  { q: "In a gentle way, you can shake the world.", a: "Mahatma Gandhi" },
  { q: "Live simply so that others may simply live.", a: "Mahatma Gandhi" },
  { q: "There is more to life than increasing its speed.", a: "Mahatma Gandhi" },
  { q: "It is health that is real wealth and not pieces of gold and silver.", a: "Mahatma Gandhi" },
  { q: "A no uttered from the deepest conviction is better than a yes merely to please.", a: "Mahatma Gandhi" },
  { q: "Peace is not something you wish for; it's something you make.", a: "Robert Fulghum" },
  { q: "In a world where you can be anything, be kind.", a: "Jennifer Dukes Lee" },
  { q: "No act of kindness, no matter how small, is ever wasted.", a: "Aesop" },
  { q: "Slow and steady wins the race.", a: "Aesop" },
  { q: "Appearances often are deceiving.", a: "Aesop" },
  { q: "It is thrifty to prepare today for the wants of tomorrow.", a: "Aesop" },
  { q: "United we stand, divided we fall.", a: "Aesop" },
  { q: "Every truth has two sides; it is as well to look at both, before we commit ourselves to either.", a: "Aesop" },
  { q: "The gods help them that help themselves.", a: "Aesop" },
  { q: "No one is useless in this world who lightens the burdens of another.", a: "Charles Dickens" },
  { q: "It was the best of times, it was the worst of times.", a: "Charles Dickens" },
  { q: "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.", a: "Charles Dickens" },
  { q: "Reflect upon your present blessings, of which every man has many.", a: "Charles Dickens" },
  { q: "In love of home, the love of country has its rise.", a: "Charles Dickens" },
  { q: "It is not a bad thing that children should occasionally, and politely, put parents in their place.", a: "Charles Dickens" },
  { q: "Life is a series of natural and spontaneous changes. Don't resist them.", a: "Lao Tzu" },
  { q: "Nature does not hurry, yet everything is accomplished.", a: "Lao Tzu" },
  { q: "Silence is a source of great strength.", a: "Lao Tzu" },
  { q: "A good traveler has no fixed plans and is not intent upon arriving.", a: "Lao Tzu" },
  { q: "Care about what other people think and you will always be their prisoner.", a: "Lao Tzu" },
  { q: "The best fighter is never angry.", a: "Lao Tzu" },
  { q: "To the mind that is still, the whole universe surrenders.", a: "Lao Tzu" },
  { q: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", a: "Lao Tzu" },
  { q: "New beginnings are often disguised as painful endings.", a: "Lao Tzu" },
  { q: "The wise man is one who knows what he does not know.", a: "Lao Tzu" },
  { q: "A leader is best when people barely know that he exists.", a: "Lao Tzu" },
  { q: "The soul that sees beauty may sometimes walk alone.", a: "Johann Wolfgang von Goethe" },
  { q: "None are more hopelessly enslaved than those who falsely believe they are free.", a: "Johann Wolfgang von Goethe" },
  { q: "Everything is hard before it is easy.", a: "Johann Wolfgang von Goethe" },
  { q: "Man's best friends are his ten fingers.", a: "Johann Wolfgang von Goethe" },
  { q: "As soon as you trust yourself, you will know how to live.", a: "Johann Wolfgang von Goethe" },
  { q: "Correction does much, but encouragement does more.", a: "Johann Wolfgang von Goethe" },
  { q: "He who moves not forward, goes backward.", a: "Johann Wolfgang von Goethe" },
  { q: "Nothing is worth more than this day.", a: "Johann Wolfgang von Goethe" },
  { q: "Divide and rule, a sound motto. Unite and lead, a better one.", a: "Johann Wolfgang von Goethe" },
  { q: "It is not enough to know, we must also apply.", a: "Johann Wolfgang von Goethe" },
  { q: "Miracles happen to those who believe in them.", a: "Bernard Berenson" },
  { q: "Faith is taking the first step even when you can't see the whole staircase.", a: "Martin Luther King Jr." },
  { q: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Chinese Proverb" },
  { q: "Fall down seven times, stand up eight.", a: "Japanese Proverb" },
  { q: "A single arrow is easily broken, but not ten in a bundle.", a: "Japanese Proverb" },
  { q: "The bamboo that bends is stronger than the oak that resists.", a: "Japanese Proverb" },
  { q: "Vision without action is a daydream. Action without vision is a nightmare.", a: "Japanese Proverb" },
  { q: "If you want to go fast, go alone. If you want to go far, go together.", a: "African Proverb" },
  { q: "However far you have gone on a wrong road, turn back.", a: "Turkish Proverb" },
  { q: "A river cuts through rock, not because of its power, but because of its persistence.", a: "James N. Watkins" },
  { q: "The only person you should try to be better than is who you were yesterday.", a: "Anonymous" },
  { q: "What you get by achieving your goals is not as important as what you become by achieving your goals.", a: "Zig Ziglar" },
  { q: "Don't watch the clock; do what it does. Keep going.", a: "Sam Levenson" },
  { q: "Time you enjoy wasting is not wasted time.", a: "Marthe Troly-Curtin" },
  { q: "Lost time is never found again.", a: "Benjamin Franklin" },
  { q: "The two most important days in your life are the day you are born and the day you find out why.", a: "Mark Twain" },
  { q: "Kindness is the language which the deaf can hear and the blind can see.", a: "Mark Twain" },
  { q: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", a: "Mark Twain" },
  { q: "Courage is resistance to fear, mastery of fear, not absence of fear.", a: "Mark Twain" },
  { q: "The person who does not read has no advantage over the person who cannot read.", a: "Mark Twain" },
  { q: "Get a good idea and stay with it. Dog it, and work at it until it's done right.", a: "Walt Disney" },
  { q: "Around here, however, we don't look backwards for very long. We keep moving forward.", a: "Walt Disney" },
  { q: "When you're curious, you find lots of interesting things to do.", a: "Walt Disney" },
  { q: "Times and conditions change so rapidly that we must keep our aim constantly focused on the future.", a: "Walt Disney" },
  { q: "You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you.", a: "Walt Disney" },
  { q: "There is more treasure in books than in all the pirate's loot on Treasure Island.", a: "Walt Disney" },
  { q: "Curiosity keeps leading us down new paths.", a: "Walt Disney" },
  { q: "First, think. Second, believe. Third, dream. And finally, dare.", a: "Walt Disney" },
  { q: "All the adversity I've had in my life, all my troubles and obstacles, have strengthened me.", a: "Walt Disney" },
  { q: "Do one thing every day that scares you.", a: "Eleanor Roosevelt" },
  { q: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", a: "Ralph Waldo Emerson" },
  { q: "Adopt the pace of nature: her secret is patience.", a: "Ralph Waldo Emerson" },
  { q: "For every minute you remain angry, you give up sixty seconds of peace of mind.", a: "Ralph Waldo Emerson" },
  { q: "The only way to have a friend is to be one.", a: "Ralph Waldo Emerson" },
  { q: "Every artist was first an amateur.", a: "Ralph Waldo Emerson" },
  { q: "Nothing great was ever achieved without enthusiasm.", a: "Ralph Waldo Emerson" },
  { q: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", a: "Ralph Waldo Emerson" },
  { q: "The mind, once stretched by a new idea, never returns to its original dimensions.", a: "Ralph Waldo Emerson" },
  { q: "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.", a: "Francis Chan" },
  { q: "What we think, we become.", a: "Buddha" },
  { q: "Better than a thousand hollow words, is one word that brings peace.", a: "Buddha" },
  { q: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", a: "Buddha" },
  { q: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", a: "Buddha" },
  { q: "The trouble is, you think you have time.", a: "Buddha" },
  { q: "Hatred does not cease by hatred, but only by love; this is the eternal rule.", a: "Buddha" },
  { q: "It is better to conquer yourself than to win a thousand battles.", a: "Buddha" },
  { q: "Every morning we are born again. What we do today is what matters most.", a: "Buddha" },
  { q: "Just as a candle cannot burn without fire, we cannot live without a spiritual life.", a: "Buddha" },
  { q: "The tongue like a sharp knife... kills without drawing blood.", a: "Buddha" },
  { q: "Health is the greatest gift, contentment the greatest wealth.", a: "Buddha" },
  { q: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened.", a: "Buddha" },
  { q: "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go.", a: "Buddha" },
  { q: "Let today be the day you give up who you've been for who you can become.", a: "Hal Elrod" },
  { q: "You are never too old to set another goal or to dream a new dream.", a: "C.S. Lewis" },
  { q: "Hardships often prepare ordinary people for an extraordinary destiny.", a: "C.S. Lewis" },
  { q: "There are far, far better things ahead than any we leave behind.", a: "C.S. Lewis" },
  { q: "Courage is not simply one of the virtues, but the form of every virtue at the testing point.", a: "C.S. Lewis" },
  { q: "Failures are finger posts on the road to achievement.", a: "C.S. Lewis" },
  { q: "Integrity is doing the right thing, even when no one is watching.", a: "C.S. Lewis" },
  { q: "The safest road to hell is the gradual one — the gentle slope, soft underfoot.", a: "C.S. Lewis" },
  { q: "You can't go back and change the beginning, but you can start where you are and change the ending.", a: "C.S. Lewis" },
  { q: "We are what we believe we are.", a: "C.S. Lewis" },
  { q: "Isn't it funny how day by day nothing changes, but when you look back, everything is different.", a: "C.S. Lewis" },
  { q: "It is never too late to be what you might have been.", a: "George Eliot" },
  { q: "Adventure is worthwhile in itself.", a: "Amelia Earhart" },
  { q: "The most difficult thing is the decision to act, the rest is merely tenacity.", a: "Amelia Earhart" },
  { q: "Preparation, I have often said, is rightly two-thirds of any venture.", a: "Amelia Earhart" },
  { q: "The most effective way to do it, is to do it.", a: "Amelia Earhart" },
  { q: "Courage is the price that life exacts for granting peace.", a: "Amelia Earhart" },
  { q: "Never interrupt someone doing what you said couldn't be done.", a: "Amelia Earhart" },
  { q: "I have often said that the lure of flying is the lure of beauty.", a: "Amelia Earhart" },
  { q: "One of the most reliable ways to make people believe in falsehoods is repetition.", a: "Norman Doidge" },
  { q: "Stand for something or you will fall for anything.", a: "Rosa Parks" },
  { q: "You must never be fearful about what you are doing when it is right.", a: "Rosa Parks" },
  { q: "I have learned over the years that when one's mind is made up, this diminishes fear.", a: "Rosa Parks" },
  { q: "Each person must live their life as a model for others.", a: "Rosa Parks" },
  { q: "Memories of our lives, of our works and our deeds will continue in others.", a: "Rosa Parks" },
  { q: "In order to be free, we have got to control our own bodies.", a: "Rosa Parks" },
  { q: "Have you ever seen the sky? I mean, really seen it?", a: "Anne Frank" },
  { q: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", a: "Anne Frank" },
  { q: "Think of all the beauty still left around you and be happy.", a: "Anne Frank" },
  { q: "I don't think of all the misery, but of the beauty that still remains.", a: "Anne Frank" },
  { q: "Laziness may appear attractive, but work gives satisfaction.", a: "Anne Frank" },
  { q: "In spite of everything, I still believe that people are really good at heart.", a: "Anne Frank" },
  { q: "Whoever is happy will make others happy too.", a: "Anne Frank" },
  { q: "It's really a wonder that I haven't dropped all my ideals, because they seem so absurd and impossible to carry out.", a: "Anne Frank" },
  { q: "The final forming of a person's character lies in their own hands.", a: "Anne Frank" },
  { q: "Where there is hope, there is life. It fills us with fresh courage and makes us strong again.", a: "Anne Frank" },
  { q: "You know, I feel like a lion. I have to fight and I have to be brave.", a: "Malala Yousafzai" },
  { q: "When the whole world is silent, even one voice becomes powerful.", a: "Malala Yousafzai" },
  { q: "I raise up my voice — not so that I can shout, but so that those without a voice can be heard.", a: "Malala Yousafzai" },
  { q: "We realize the importance of our voice only when we are silenced.", a: "Malala Yousafzai" },
  { q: "One child, one teacher, one book, one pen can change the world.", a: "Malala Yousafzai" },
  { q: "There is a moment when you have to choose whether to be silent or to stand up.", a: "Malala Yousafzai" },
  { q: "Let us pick up our books and our pens, they are the most powerful weapons.", a: "Malala Yousafzai" },
  { q: "I don't want to be remembered as the girl who was shot. I want to be remembered as the girl who fought.", a: "Malala Yousafzai" },
  { q: "The middle path is the way to wisdom.", a: "Rumi" },
  { q: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", a: "Rumi" },
  { q: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", a: "Rumi" },
  { q: "The wound is the place where the light enters you.", a: "Rumi" },
  { q: "You were born with wings, why prefer to crawl through life?", a: "Rumi" },
  { q: "Do not feel lonely, the entire universe is inside you.", a: "Rumi" },
  { q: "Let yourself be silently drawn by the strange pull of what you really love.", a: "Rumi" },
  { q: "When you do things from your soul, you feel a river moving in you, a joy.", a: "Rumi" },
  { q: "Respond to every call that excites your spirit.", a: "Rumi" },
  { q: "Sell your cleverness and buy bewilderment.", a: "Rumi" },
  { q: "Out beyond ideas of wrongdoing and rightdoing there is a field. I'll meet you there.", a: "Rumi" },
  { q: "Be like a tree and let the dead leaves drop.", a: "Rumi" },
  { q: "The quieter you become, the more you are able to hear.", a: "Rumi" },
  { q: "Beauty surrounds us, but usually we need to be walking in a garden to know it.", a: "Rumi" },
  { q: "Keep is what you are seeking is also seeking you.", a: "Rumi" },
  { q: "Silence is the language of god, all else is poor translation.", a: "Rumi" },
  { q: "In your light I learn how to love. In your beauty, how to make poems.", a: "Rumi" },
  { q: "Do not worry, in the end, everything works out.", a: "Khalil Gibran" },
  { q: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", a: "Khalil Gibran" },
  { q: "Your living is determined not so much by what life brings to you as by the attitude you bring to life.", a: "Khalil Gibran" },
  { q: "The obstacle is the path.", a: "Khalil Gibran" },
  { q: "A little knowledge that acts is worth infinitely more than much knowledge that is idle.", a: "Khalil Gibran" },
  { q: "Progress lies not in enhancing what is, but in advancing toward what will be.", a: "Khalil Gibran" },
  { q: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", a: "Winston Churchill" },
  { q: "We make a living by what we get, but we make a life by what we give.", a: "Winston Churchill" },
  { q: "Success consists of going from failure to failure without loss of enthusiasm.", a: "Winston Churchill" },
  { q: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", a: "Winston Churchill" },
  { q: "Kites rise highest against the wind, not with it.", a: "Winston Churchill" },
  { q: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", a: "Winston Churchill" },
  { q: "The price of greatness is responsibility.", a: "Winston Churchill" },
  { q: "Never let a good crisis go to waste.", a: "Winston Churchill" },
  { q: "Difficulties mastered are opportunities won.", a: "Winston Churchill" },
  { q: "Success is going from failure to failure without losing your enthusiasm.", a: "Winston Churchill" },
  { q: "Success is not permanent, and failure isn't final.", a: "Mike Ditka" },
  { q: "Difficult roads often lead to beautiful destinations.", a: "Zig Ziglar" },
  { q: "You don't need to see the whole staircase, just take the first step.", a: "Martin Luther King Jr." },
  { q: "Perseverance is not a long race; it is many short races one after the other.", a: "Walter Elliot" },
  { q: "It's not that I'm so smart, it's just that I stay with problems longer.", a: "Albert Einstein" },
  { q: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", a: "Albert Einstein" },
  { q: "In the midst of every crisis, lies great opportunity.", a: "Albert Einstein" },
  { q: "I have no special talent. I am only passionately curious.", a: "Albert Einstein" },
  { q: "Strive not to be a success, but rather to be of value.", a: "Albert Einstein" },
  { q: "A ship is always safe at shore, but that is not what it is built for.", a: "Albert Einstein" },
  { q: "Weakness of attitude becomes weakness of character.", a: "Albert Einstein" },
  { q: "Anyone who has never made a mistake has never tried anything new.", a: "Albert Einstein" },
  { q: "If you can't explain it simply, you don't understand it well enough.", a: "Albert Einstein" },
  { q: "Learn from yesterday, live for today, hope for tomorrow.", a: "Albert Einstein" },
  { q: "Reality is merely an illusion, albeit a very persistent one.", a: "Albert Einstein" },
  { q: "Small opportunities are often the beginning of great enterprises.", a: "Demosthenes" },
  { q: "The chief danger in life is that you may take too many precautions.", a: "Alfred Adler" },
  { q: "Trust because you are willing to accept the risk, not because it's safe or certain.", a: "Anonymous" },
  { q: "It is not the mountain we conquer but ourselves.", a: "Edmund Hillary" },
  { q: "Because it's there.", a: "George Mallory" },
  { q: "That's one small step for man, one giant leap for mankind.", a: "Neil Armstrong" },
  { q: "Mystery creates wonder and wonder is the basis of man's desire to understand.", a: "Neil Armstrong" },
  { q: "Research is creating new knowledge.", a: "Neil Armstrong" },
  { q: "I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.", a: "Neil Armstrong" },
  { q: "The important achievement of Apollo was demonstrating that humanity is not forever chained to this planet.", a: "Neil Armstrong" },
  { q: "For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will follow, the experience most certainly changes your perspective.", a: "Sally Ride" },
  { q: "Do not let what you cannot do interfere with what you can do.", a: "John Wooden" },
  { q: "It's what you learn after you know it all that counts.", a: "John Wooden" },
  { q: "Things turn out best for the people who make the best of the way things turn out.", a: "John Wooden" },
  { q: "Failing to prepare is preparing to fail.", a: "John Wooden" },
  { q: "Don't let making a living prevent you from making a life.", a: "John Wooden" },
  { q: "Success is peace of mind, which is a direct result of self-satisfaction in knowing you did your best.", a: "John Wooden" },
  { q: "Talent is God-given; be humble. Fame is man-given; be grateful. Conceit is self-given; be careful.", a: "John Wooden" },
  { q: "You can't let praise or criticism get to you. It's a weakness to get caught up in either one.", a: "John Wooden" },
  { q: "Be more concerned with your character than your reputation.", a: "John Wooden" },
  { q: "The true athletic hero is a marker in humanity, a person against whom we can measure ourselves.", a: "Jesse Owens" },
  { q: "Friendships born on the field of athletic strife are the real gold of competition.", a: "Jesse Owens" },
  { q: "We all have dreams. But in order to make dreams come into reality, it takes an awful lot of determination.", a: "Jesse Owens" },
  { q: "Find something that you love to do and you'll never have to work a day in your life.", a: "Harvey Mackay" },
  { q: "It's never too late to be who you might have been.", a: "George Eliot" },
  { q: "Character is like a tree and reputation like its shadow. The shadow is what we think of it; the tree is the real thing.", a: "Abraham Lincoln" },
  { q: "A house divided against itself cannot stand.", a: "Abraham Lincoln" },
  { q: "In the end, it's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { q: "Most folks are about as happy as they make up their minds to be.", a: "Abraham Lincoln" },
  { q: "I am not bound to win, but I am bound to be true.", a: "Abraham Lincoln" },
  { q: "Better to remain silent and be thought a fool than to speak out and remove all doubt.", a: "Abraham Lincoln" },
  { q: "The best thing about the future is that it comes one day at a time.", a: "Abraham Lincoln" },
  { q: "It is not the critic who counts... The credit belongs to the man who is actually in the arena.", a: "Theodore Roosevelt" },
  { q: "The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood.", a: "Theodore Roosevelt" },
  { q: "In any moment of decision, the best thing you can do is the right thing.", a: "Theodore Roosevelt" },
  { q: "Get action. Seize the moment. Man was never intended to become an oyster.", a: "Theodore Roosevelt" },
  { q: "Nothing in the world is worth having or worth doing unless it means effort, pain, or difficulty.", a: "Theodore Roosevelt" },
  { q: "Aggressive fighting for the right is the noblest sport the world affords.", a: "Theodore Roosevelt" },
  { q: "Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure.", a: "Theodore Roosevelt" },
  { q: "There is no scientific answer for success. You can't define it. You just have to live it and do it.", a: "Anita Roddick" },
  { q: "Choose a job you love, and you will never have to work a day in your life.", a: "Confucius" },
  { q: "The superior man is modest in his speech, but exceeds in his actions.", a: "Confucius" },
  { q: "Real knowledge is to know the extent of one's ignorance.", a: "Confucius" },
  { q: "The gem cannot be polished without friction, nor man perfected without trials.", a: "Confucius" },
  { q: "It does not matter how slowly you go so long as you do not stop.", a: "Confucius" },
  { q: "Wheresoever you go, go with all your heart.", a: "Confucius" },
  { q: "He who wishes to secure the good of others has already secured his own.", a: "Confucius" },
  { q: "Success depends upon previous preparation, and without such preparation there is sure to be failure.", a: "Confucius" },
  { q: "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.", a: "Confucius" },
  { q: "By three methods we may learn wisdom: first, by reflection; second, by imitation; third, by experience.", a: "Confucius" },
  { q: "The man who says he can, and the man who says he cannot, are both correct.", a: "Confucius" },
  { q: "To be wronged is nothing unless you continue to remember it.", a: "Confucius" },
  { q: "A man who has committed a mistake and doesn't correct it, is committing another mistake.", a: "Confucius" },
  { q: "Everything has beauty, but not everyone can see it.", a: "Confucius" },
  { q: "Silence is a true friend who never betrays.", a: "Confucius" },
  { q: "Only the wisest and stupidest of men never change.", a: "Confucius" },
  { q: "If you make a mistake and do not correct it, this is called a mistake.", a: "Confucius" },
  { q: "The will to win, the desire to succeed, the urge to reach your full potential — these are the keys.", a: "Confucius" },
  { q: "The superior man thinks always of virtue; the common man thinks of comfort.", a: "Confucius" },
  { q: "Study the past if you would define the future.", a: "Confucius" },
];

// Deterministic day-count index — a pure function of the calendar date, so
// every device shows the same quote on the same day without any syncing.
// dayKey is the app's own study-day format ('YYYY-MM-DD', already offset by
// the day's reset hour), reused here just to parse a date, not for its
// study-day meaning.
function quoteForDay(dayKey) {
  const d = dayKeyToDate(dayKey);
  const dayCount = Math.floor(d.getTime() / 86400000);
  const i = ((dayCount % QUOTES.length) + QUOTES.length) % QUOTES.length;
  return QUOTES[i];
}
